#!/bin/sh
is_first_boot=`uci -q get zz_config.@status[0].first_boot`
if test $is_first_boot -gt 0; then
# uci del dhcp.lan.ra_slaac
# uci set network.lan.ipaddr='10.0.0.1'
uci add_list network.lan.ip6class='USBv6'
uci add_list network.lan.ip6class='wan6'
# uci set luci.main.lang='zh_cn'
# uci set luci.main.mediaurlbase='/luci-static/argon'
# uci set cpufreq.global.set='1'
# uci set cpufreq.cpufreq.minfreq0='600000'
# uci set cpufreq.cpufreq.maxfreq0='1608000'
# uci set luci-fan.@luci-fan[0]=luci-fan
# uci set luci-fan.@luci-fan[0].enabled='1'
# uci set luci-fan.@luci-fan[0].off_temp='10'
# uci set luci-fan.@luci-fan[0].on_temp='25'
# uci set qmodem.main.at_tool='1'
# uci set qmodem.main.start_delay='15'
# uci set qmodem.main.enable_pcie_scan='0'
# uci set qmodem.main.enable_usb_scan='1'

uci delete mwan3.@rule[-1]
uci delete mwan3.@rule[-1]
uci delete mwan3.@rule[-1]
uci delete mwan3.@rule[-1]
uci delete mwan3.@rule[-1]
uci delete mwan3.@policy[-1]
uci delete mwan3.@policy[-1]
uci delete mwan3.@policy[-1]
uci delete mwan3.@policy[-1]
uci delete mwan3.@policy[-1]
uci delete mwan3.@policy[-1]
uci delete mwan3.@member[-1]
uci delete mwan3.@member[-1]
uci delete mwan3.@member[-1]
uci delete mwan3.@member[-1]
uci delete mwan3.@member[-1]
uci delete mwan3.@member[-1]
uci delete mwan3.@member[-1]
uci delete mwan3.@member[-1]
uci delete mwan3.@member[-1]
uci delete mwan3.@member[-1]
uci delete mwan3.@member[-1]
uci delete mwan3.@member[-1]
uci delete mwan3.@member[-1]
uci delete mwan3.@member[-1]
uci delete mwan3.@member[-1]
uci delete mwan3.@interface[-1]
uci delete mwan3.@interface[-1]
uci delete mwan3.@interface[-1]
uci delete mwan3.@interface[-1]
uci delete mwan3.@interface[-1]
uci commit mwan3

# uci del qmodem_mwan.global.enable_mwan

uci add_list qmodem_mwan.@ipv4[-1].member_track_ip='119.29.29.29'

uci set qmodem_mwan.global.enable_mwan='1'
uci set qmodem_mwan.global.sticky_mode='0'
uci add qmodem_mwan ipv4
uci set qmodem_mwan.@ipv4[-1].member_priority='1'
uci set qmodem_mwan.@ipv4[-1].member_weight='1'
uci set qmodem_mwan.@ipv4[-1].member_interface='USB'
uci add_list qmodem_mwan.@ipv4[-1].member_track_ip='test.ustc.edu.cn'
uci add_list qmodem_mwan.@ipv4[-1].member_track_ip='cip.cc'
uci add_list qmodem_mwan.@ipv4[-1].member_track_ip='208.67.222.222'
uci add_list qmodem_mwan.@ipv4[-1].member_track_ip='208.67.220.220'
uci add_list qmodem_mwan.@ipv4[-1].member_track_ip='119.29.29.29'
uci set qmodem_mwan.@ipv4[-1].member_priority='50'

uci add system led
uci set system.@led[-1].name='net'
uci set system.@led[-1].sysfs='LED-3'
uci set system.@led[-1].trigger='netdev'
uci set system.@led[-1].dev='br-lan'
uci add_list system.@led[-1].mode='link'
uci add_list system.@led[-1].mode='tx'
uci add_list system.@led[-1].mode='rx'
uci add system led
uci set system.@led[-1].name='heartbeat'
uci set system.@led[-1].sysfs='LED-4'
uci set system.@led[-1].trigger='heartbeat'
uci set system.@led[-1].inverted='1'

uci set attendedsysupgrade.client.login_check_for_upgrades='0'

uci commit

/etc/init.d/network reload
wifi
service qmodem_mwan restart

fi